config/routes.rb
Unifloor::Application.routes.draw do

  devise_for :users

  resources :messages

  resources :associates
  namespace :users do
    resources :stocks
    resources :products
    resources :orders
    resources :categories
    resources :customers
    resources :employees
    resources :admins
    resources :representatives
    root :to => 'dashboards#index'
  end
  match "/produtos" => "pages#products"
  match "/acessorios" => "pages#accessories"
  match "/contato" => "pages#contact"
  match "/unifloor" => "pages#unifloor"
  
  root :to => 'pages#home'
end

app/models/category.rb
class Category < ActiveRecord::Base
end

app/models/customer.rb
class Customer < ActiveRecord::Base
end

app/models/message.rb
class Message < ActiveRecord::Base
	validates_presence_of :name, :message => "Digite seu nome"
	validates_presence_of :mail, :message => "Digite seu E-mail"
	validates_presence_of :message, :message => "Digite uma menssagem"
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :customer
  belongs_to :user
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :category
  has_one :stock
end

app/models/representative.rb
class Representative < ActiveRecord::Base
  has_many :order
end

app/models/stock.rb
class Stock < ActiveRecord::Base
  belongs_to :product
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :access_type,
   :representative, :representative_attributes, :name
  
  has_one :representative
  
  accepts_nested_attributes_for :representative
  def self.get_representatives
    where("access_type = ?", AccessTypes::REPRESENTATIVE)
  end
  
  def self.get_employees
    where("access_type = ?", AccessTypes::EMPLOYEE)
  end
  
  def self.get_admins
    where("access_type = ?", AccessTypes::ADMIN)
  end
end

app/models/users.rb
module Users
  def self.table_name_prefix
    'users_'
  end
end

app/controllers/application_controller.rb
# -*- encoding : utf-8 -*-
class ApplicationController < ActionController::Base
  protect_from_forgery
  respond_to :html, :json
  
  def after_sign_in_path_for(resource)
    users_root_path
  end
  
  def can_handle?(resource)
    if current_user.access_type == AccessTypes::REPRESENTATIVE
      default_redirect unless representative_has_privilege?(resource)
    elsif current_user.access_type == AccessTypes::EMPLOYEE
      default_redirect unless employee_has_privilege?(resource)
    elsif current_user.access_type == AccessTypes::ADMIN
      true
    end
    false
  end

  def representative_has_privilege?(resource)
    [:product, :category, :order, :customer].include? resource
  end
  
  def employee_has_privilege?(resource)
    [:product, :category, :order, :customer, :representative, :stock,
       :employee].include? resource
  end
  
  def default_redirect
    redirect_to users_root_path, notice: 'Você não tem permissão para acessar esse recurso'
  end
end

app/controllers/associates_controller.rb
class AssociatesController < ApplicationController
  
  def index
    @admins = User.get_admins
    @representatives = User.get_representatives
    @employees = User.get_employees
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def create
    @message = Message.new(params[:message])
    if @message.save
      UnifloorContact.mail_contact(@message).deliver
      redirect_to message_path(@message)
    else
      redirect_to :back
    end
  end

  def show
    @message = Message.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @title = "Home"
    redirect_to  users_root_path if current_user
  end

  def products
    @title = "Produtos"
  end

  def accessories
    @title = "Acessorios"
  end

  def contact
    @title = "Contato"
  end

  def unifloor
    @title = "Sobre a UniFloor"
  end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/associates_helper.rb
module AssociatesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/helpers/users/orders_helper.rb
module Users::OrdersHelper
end

app/views/layouts/_footer.html.haml
%section.footer
  %address
    %p Av. Paulista, 807 - Cj. 610 - CEP: 01311-915
    %p São Paulo / SP - Brasil - Tel: (11) 3541-3313
  %p
    = link_to "login", new_user_session_path unless current_user
    = link_to "logout", destroy_user_session_path, method: :delete if current_user

app/views/layouts/_header.html.haml
.logo
  %h1 Unifloor , piso laminado
  #{link_to " ", root_path}
  %hr
%hr.right
%nav.header
  #{link_to "Home", root_path, :title =>"Home"}
  #{link_to "UniFloor", "/unifloor", :title =>"Unifloor" }
  #{link_to "Produtos", "/produtos", :title =>"Produtos" }
  #{link_to "Acessórios", "/acessorios", :title =>"Acessórios" }
  #{link_to "Contato", "/contato", :title =>"Contato" }

app/views/layouts/_header_user.html.haml
%header.user
  .left
    %h2 Painel de Controle
    %hr
  %nav.header
    %ul
      %li
        = link_to "Associados", associates_path
      %li
        = link_to 'Clientes', users_customers_path
      %li
        = link_to 'Categorias', users_categories_path
      %li
        = link_to 'Produtos', users_products_path
      %li
        = link_to 'Pedidos', users_orders_path
      %li.last
        = link_to 'Estoque', users_stocks_path
  .logo
    %h1 Unifloor , piso laminado
    #{link_to " ", root_path}
  %hr.right
  

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title 
      UniFloor | #{@title}
    =stylesheet_link_tag    "application", :media => "all"
    =stylesheet_link_tag    "dropkick"
    <meta name="google-site-verification" content="7yKr3LRahAG7HvFtLmDzUGOOEUKb9SKTzsXvLJQ-5a8" /> 
    =csrf_meta_tags 
  %body
    .container
      - if current_user
        %header
          =render 'layouts/header_user'
      - else
        %header
          =render 'layouts/header'
      =yield 
      %footer
        =render 'layouts/footer'
    =javascript_include_tag "application"
    =javascript_include_tag "jquery.dropkick-1.0.0"

    = yield :javascripts

app/views/unifloor_contact/mail_contact.haml
%h2{ :style => "font-size: 20px; color: #009C57;"} UniFloor
%p
	%b{ :style => "font-size: 15px; color: #009C57;"} Nome: 
	= @message.name
%p
	%b{ :style => "font-size: 15px; color: #009C57;"} E-mail: 
	= @message.mail
%p
	%b{ :style => "font-size: 15px; color: #009C57;"} Assunto: 
	= @message.subj
%p
	%b{ :style => "font-size: 15px; color: #009C57;"} Mensagem: 
	= @message.message